const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),keys={};let state='menu',startAt=0,last=performance.now(),countValue=3,sound=true;
const touchInput={up:false,down:false,left:false,right:false};let touchPointer=null,touchOrigin=null;const touchPad=$('#touchPad');

const trackPoints=[{x:0,y:-900,width:270},{x:430,y:-830,width:270},{x:760,y:-440,width:250},{x:740,y:80,width:245},{x:410,y:600,width:270},{x:-190,y:740,width:280},{x:-710,y:440,width:255},{x:-820,y:-170,width:250},{x:-520,y:-690,width:265},{x:-130,y:-970,width:275}];
const ROAD_LIMIT=.55,OFFROAD_LIMIT=1.22,wrap=n=>((n%1)+1)%1,pointAt=i=>trackPoints[(i+trackPoints.length)%trackPoints.length];
function catmull(a,b,c,d,t){const t2=t*t,t3=t2*t;return .5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t2+(-a+3*b-3*c+d)*t3)}
function trackPosition(t){const n=trackPoints.length,u=wrap(t)*n,i=Math.floor(u),f=u-i,a=pointAt(i-1),b=pointAt(i),c=pointAt(i+1),d=pointAt(i+2);return{x:catmull(a.x,b.x,c.x,d.x,f),y:catmull(a.y,b.y,c.y,d.y,f),width:(b.width+(c.width-b.width)*f)*1.35}}
function sampleTrack(t){const p=trackPosition(t),a=trackPosition(t-.0008),b=trackPosition(t+.0008),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;return{...p,t:wrap(t),dirX:dx/len,dirY:dy/len,rightX:-dy/len,rightY:dx/len,angle:Math.atan2(dx,-dy)}}
const TRACK_SAMPLES=160,GRASS_CRAWL_SPEED=44,trackSamples=Array.from({length:TRACK_SAMPLES},(_,i)=>sampleTrack(i/TRACK_SAMPLES));
function nearestTrack(x,y){let best;for(const p of trackSamples){const dx=x-p.x,dy=y-p.y,d2=dx*dx+dy*dy;if(!best||d2<best.d2)best={p,d2}}const distance=Math.sqrt(best.d2);return{...best,distance,onRoad:distance<=best.p.width*ROAD_LIMIT}}
const player={x:0,y:0,angle:0,speed:0,maxSpeed:205,reverseSpeed:68,acceleration:112,brakePower:240,friction:40,turnSpeed:2.9,lap:1,trackT:.018,lastTrackT:.018,onRoad:true,boost:0,best:null,lapStart:0,hitFlash:0,boundaryFlash:0,collisionCooldown:0};
function setPlayerStart(){const p=sampleTrack(.018);Object.assign(player,{x:p.x,y:p.y,angle:p.angle,speed:0,lap:1,trackT:p.t,lastTrackT:p.t,onRoad:true,boost:0,best:null,lapStart:0,hitFlash:0,boundaryFlash:0,collisionCooldown:0})}setPlayerStart();
const boostPads=[.17,.47,.76].map((t,i)=>({...sampleTrack(t),t,radius:78,armed:true,color:i===1?'#ff8b35':'#ffe45c'}));
const obstacles=[.29,.58,.88].map((t,i)=>{const p=sampleTrack(t),side=i%2?-1.22:1.22;return{x:p.x+p.rightX*p.width*side,y:p.y+p.rightY*p.width*side,radius:34,color:i%2?'#ff2d8d':'#21e6ff'}});
const rivals=Array.from({length:5},(_,i)=>({t:.05+i*.105,lap:1,speed:122+i*7,x:0,y:0,angle:0,color:['#ff2d8d','#ffd83d','#21e6ff','#8e61ff','#ff713d'][i]}));
const scenery=Array.from({length:42},(_,i)=>{const p=sampleTrack(i/42+.013),side=i%2?1:-1,offset=p.width*(1.32+(i%4)*.18);return{x:p.x+p.rightX*offset*side,y:p.y+p.rightY*offset*side,size:45+(i%3)*19,color:side>0?'#21e6ff':'#ff2d8d'}});
function syncRival(r){const p=sampleTrack(r.t);r.x=p.x;r.y=p.y;r.angle=p.angle}rivals.forEach(syncRival);

function resize(){const d=Math.min(devicePixelRatio,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key.toLowerCase(),release=()=>keys[k]=false;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true;b.setPointerCapture(e.pointerId)});b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});document.addEventListener('visibilitychange',()=>{if(document.hidden){Object.keys(keys).forEach(k=>keys[k]=false);resetTouchPad()}});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=`SOUND ${sound?'ON':'OFF'}`};$('#startBtn').onclick=startRace;$('#restartBtn').onclick=startRace;$('#restartRaceBtn').onclick=startRace;
function beep(freq,d=.08){if(!sound)return;const a=beep.a||(beep.a=new AudioContext),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function startRace(){resetTouchPad();setPlayerStart();boostPads.forEach(b=>b.armed=true);rivals.forEach((r,i)=>{r.t=wrap(.06+i*.105);r.lap=1;syncRival(r)});$('#startScreen').classList.remove('show');$('#finishScreen').classList.remove('show');state='countdown';countValue=3;startAt=performance.now();showCount('3');beep(220)}
function showCount(t){const el=$('#countdown');el.textContent=t;el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop')}
function format(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,x=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}

function update(dt,now){
 if(state==='countdown'){const elapsed=(now-startAt)/1000,newCount=3-Math.floor(elapsed);if(newCount!==countValue&&newCount>0){countValue=newCount;showCount(String(newCount));beep(260+(3-newCount)*110)}if(elapsed>=3){showCount('GO!');beep(660,.16);state='race';startAt=now;player.lapStart=now}return}if(state!=='race')return;
 const up=keys.arrowup||keys.w||touchInput.up,down=keys.arrowdown||keys.s||touchInput.down,left=keys.arrowleft||keys.a||touchInput.left,right=keys.arrowright||keys.d||touchInput.right,before=nearestTrack(player.x,player.y);player.onRoad=before.onRoad;
 if(up)player.speed+=player.acceleration*dt;else if(player.speed>0)player.speed-=player.friction*dt;else if(player.speed<0)player.speed+=player.friction*dt;if(down){if(player.speed>0)player.speed-=player.brakePower*dt;else player.speed-=player.acceleration*.72*dt}
 if(!player.onRoad&&player.speed>GRASS_CRAWL_SPEED)player.speed=Math.max(GRASS_CRAWL_SPEED,player.speed-260*dt);const surfaceMax=player.onRoad?player.maxSpeed:GRASS_CRAWL_SPEED,boostMax=player.onRoad&&player.boost>0?player.maxSpeed*1.28:surfaceMax;if(player.speed>boostMax)player.speed=Math.max(boostMax,player.speed-player.brakePower*dt);if(player.speed<-player.reverseSpeed)player.speed=-player.reverseSpeed;if(Math.abs(player.speed)<2&&!up&&!down)player.speed=0;
 const steer=(right?1:0)-(left?1:0),turnScale=.65+Math.min(1,Math.abs(player.speed)/player.maxSpeed)*.45;player.angle+=steer*player.turnSpeed*turnScale*dt*(player.speed>=0?1:-1);player.x+=Math.sin(player.angle)*player.speed*dt;player.y-=Math.cos(player.angle)*player.speed*dt;
 player.collisionCooldown=Math.max(0,player.collisionCooldown-dt);if(!player.collisionCooldown)for(const o of obstacles){const dx=player.x-o.x,dy=player.y-o.y,d=Math.hypot(dx,dy);if(d<o.radius+26){const fallbackX=-Math.sin(player.angle),fallbackY=Math.cos(player.angle),nx=d?dx/d:fallbackX,ny=d?dy/d:fallbackY;player.x=o.x+nx*(o.radius+27);player.y=o.y+ny*(o.radius+27);player.speed=-Math.max(24,Math.min(52,Math.abs(player.speed)*.22));player.collisionCooldown=.22;player.hitFlash=1;beep(105,.09);break}}
 let near=nearestTrack(player.x,player.y);if(near.distance>near.p.width*OFFROAD_LIMIT){const dx=player.x-near.p.x,dy=player.y-near.p.y,d=near.distance||1;player.x=near.p.x+dx/d*near.p.width*OFFROAD_LIMIT;player.y=near.p.y+dy/d*near.p.width*OFFROAD_LIMIT;player.speed=0;player.boundaryFlash=1;near=nearestTrack(player.x,player.y);beep(150,.07)}player.onRoad=near.onRoad;player.trackT=near.p.t;boostPads.forEach(b=>{const d=Math.hypot(player.x-b.x,player.y-b.y);if(d>b.radius*1.7)b.armed=true;if(d<b.radius&&b.armed){b.armed=false;player.boost=1.5;player.speed=Math.max(player.speed,player.maxSpeed*1.14);beep(880,.12)}});player.boost=Math.max(0,player.boost-dt);player.hitFlash=Math.max(0,player.hitFlash-dt*2.8);player.boundaryFlash=Math.max(0,player.boundaryFlash-dt*2.2);
 if(player.trackT<.12&&player.lastTrackT>.88&&player.speed>20&&player.onRoad){const lapTime=now-player.lapStart;player.best=player.best?Math.min(player.best,lapTime):lapTime;player.lapStart=now;if(player.lap>=3){finish(now);return}player.lap++}player.lastTrackT=player.trackT;
 rivals.forEach((r,i)=>{const old=r.t;r.speed=132+i*4+Math.sin(now/800+i)*7;r.t=wrap(r.t+r.speed*dt/6500);if(r.t<.12&&old>.88)r.lap++;syncRival(r)});const meScore=(player.lap-1)+player.trackT,ahead=rivals.filter(r=>(r.lap-1)+r.t>meScore).length;$('#position').textContent=Math.min(6,ahead+1);$('#lap').textContent=player.lap;$('#speed').textContent=String(Math.round(Math.abs(player.speed))).padStart(3,'0');$('#raceTime').textContent=format(now-startAt);$('#bestLap').textContent=player.best?format(player.best):'--:--.---';
}
function finish(now){state='finish';const pos=$('#position').textContent,suffix=pos==='1'?'ST':pos==='2'?'ND':pos==='3'?'RD':'TH';$('#finishPlace').textContent=pos+suffix;$('#finalTime').textContent=format(now-startAt);setTimeout(()=>$('#finishScreen').classList.add('show'),400);beep(520,.25)}

function canvasPoint(x,y){const r=canvas.getBoundingClientRect();return{x:x-r.left,y:y-r.top}}function resetTouchPad(){touchPointer=null;touchOrigin=null;Object.keys(touchInput).forEach(k=>touchInput[k]=false);touchPad.classList.remove('show');touchPad.style.setProperty('--stick-x','0px');touchPad.style.setProperty('--stick-y','0px')}
function updateTouchDrive(x,y){if(!touchOrigin)return;let dx=x-touchOrigin.x,dy=y-touchOrigin.y,len=Math.hypot(dx,dy);if(len>52){dx=dx/len*52;dy=dy/len*52}touchInput.left=dx<-10;touchInput.right=dx>10;touchInput.up=dy<-10;touchInput.down=dy>10;touchPad.style.setProperty('--stick-x',`${dx}px`);touchPad.style.setProperty('--stick-y',`${dy}px`)}function beginTouch(id,x,y){if(touchPointer!==null||(state!=='race'&&state!=='countdown'))return false;touchPointer=id;touchOrigin={x,y};touchPad.style.left=`${x}px`;touchPad.style.top=`${y}px`;touchPad.classList.add('show');updateTouchDrive(x,y);return true}function moveTouch(id,x,y){if(touchPointer!==id)return false;updateTouchDrive(x,y);return true}function endTouch(id){if(touchPointer===id)resetTouchPad()}
if(window.PointerEvent){canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const p=canvasPoint(e.clientX,e.clientY);if(beginTouch(e.pointerId,p.x,p.y)){e.preventDefault();canvas.setPointerCapture?.(e.pointerId)}});canvas.addEventListener('pointermove',e=>{const p=canvasPoint(e.clientX,e.clientY);if(moveTouch(e.pointerId,p.x,p.y))e.preventDefault()});canvas.addEventListener('pointerup',e=>endTouch(e.pointerId));canvas.addEventListener('pointercancel',e=>endTouch(e.pointerId));canvas.addEventListener('lostpointercapture',e=>endTouch(e.pointerId))}else{const findTouch=(list,id)=>Array.from(list).find(t=>t.identifier===id);canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0],p=canvasPoint(t.clientX,t.clientY);if(beginTouch(t.identifier,p.x,p.y))e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{const t=findTouch(e.changedTouches,touchPointer);if(t){const p=canvasPoint(t.clientX,t.clientY);if(moveTouch(t.identifier,p.x,p.y))e.preventDefault()}},{passive:false});canvas.addEventListener('touchend',e=>{const t=findTouch(e.changedTouches,touchPointer);if(t)endTouch(t.identifier)});canvas.addEventListener('touchcancel',()=>resetTouchPad())}

function cameraPoint(x,y,w,h){const dx=x-player.x,dy=y-player.y,s=Math.sin(player.angle),c=Math.cos(player.angle),depth=dx*s-dy*c,side=dx*c+dy*s;if(depth<68||depth>2300)return null;const scale=310/depth;return{x:w/2+side*scale,y:h*.34+172*scale,depth,scale}}
function roadQuad(a,b,w,h){const ar={x:a.x+a.rightX*a.width,y:a.y+a.rightY*a.width},al={x:a.x-a.rightX*a.width,y:a.y-a.rightY*a.width},br={x:b.x+b.rightX*b.width,y:b.y+b.rightY*b.width},bl={x:b.x-b.rightX*b.width,y:b.y-b.rightY*b.width},q=[cameraPoint(ar.x,ar.y,w,h),cameraPoint(al.x,al.y,w,h),cameraPoint(br.x,br.y,w,h),cameraPoint(bl.x,bl.y,w,h)];return q.some(v=>!v)?null:q}
function polygon(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill()}
function drawRoad(w,h){const quads=[];for(let i=0;i<trackSamples.length;i++){const q=roadQuad(trackSamples[i],trackSamples[(i+1)%trackSamples.length],w,h);if(q)quads.push({q,depth:q.reduce((n,p)=>n+p.depth,0)/4,i})}quads.sort((a,b)=>b.depth-a.depth);for(const item of quads){const q=item.q;polygon(q,item.i%6<3?'#252a35':'#20242e');if(item.i%2===0){ctx.strokeStyle='#dce6ff38';ctx.lineWidth=Math.max(1,3*q[0].scale);ctx.beginPath();ctx.moveTo(q[0].x,q[0].y);ctx.lineTo(q[2].x,q[2].y);ctx.moveTo(q[1].x,q[1].y);ctx.lineTo(q[3].x,q[3].y);ctx.stroke()}if(item.i%10<3){ctx.strokeStyle='#e5efff30';ctx.beginPath();ctx.moveTo((q[0].x+q[1].x)*.5,(q[0].y+q[1].y)*.5);ctx.lineTo((q[2].x+q[3].x)*.5,(q[2].y+q[3].y)*.5);ctx.stroke()}}}
function drawRibbon(p,width,length,color,w,h){const rx=p.rightX*width,ry=p.rightY*width,fx=p.dirX*length,fy=p.dirY*length,q=[cameraPoint(p.x-rx-fx,p.y-ry-fy,w,h),cameraPoint(p.x+rx-fx,p.y+ry-fy,w,h),cameraPoint(p.x+rx+fx,p.y+ry+fy,w,h),cameraPoint(p.x-rx+fx,p.y-ry+fy,w,h)];if(!q.some(v=>!v))polygon(q,color)}
function drawWorldObjects(w,h){const visible=[];for(const b of boostPads){const p=cameraPoint(b.x,b.y,w,h);if(p)visible.push({type:'boost',p,item:b})}for(const o of obstacles){const p=cameraPoint(o.x,o.y,w,h);if(p)visible.push({type:'obstacle',p,item:o})}for(const r of rivals){const p=cameraPoint(r.x,r.y,w,h);if(p)visible.push({type:'rival',p,item:r})}for(const t of scenery){const p=cameraPoint(t.x,t.y,w,h);if(p)visible.push({type:'tree',p,item:t})}visible.sort((a,b)=>b.p.depth-a.p.depth);for(const v of visible){const p=v.p,it=v.item;if(v.type==='boost')drawRibbon(it,it.width*.78,20,it.color,w,h);else if(v.type==='tree'){const s=Math.min(150,it.size*p.scale);ctx.fillStyle='#071522';ctx.fillRect(p.x-s*.11,p.y-s*.72,s*.22,s*.72);ctx.fillStyle=it.color+'77';ctx.shadowBlur=16;ctx.shadowColor=it.color;ctx.beginPath();ctx.moveTo(p.x,p.y-s*1.55);ctx.lineTo(p.x-s*.55,p.y-s*.48);ctx.lineTo(p.x+s*.55,p.y-s*.48);ctx.closePath();ctx.fill();ctx.shadowBlur=0}else if(v.type==='obstacle'){const s=Math.min(95,it.radius*p.scale);ctx.fillStyle='#101522';ctx.fillRect(p.x-s,p.y-s*.85,s*2,s*.85);ctx.fillStyle=it.color;ctx.shadowBlur=15;ctx.shadowColor=it.color;ctx.fillRect(p.x-s*.88,p.y-s*.72,s*1.76,s*.15);ctx.shadowBlur=0}else drawKart(p.x,p.y,Math.min(76,28*p.scale),it.color,false)}}
function drawFinish(w,h){const p=sampleTrack(0);drawRibbon(p,p.width,9,'#f4f6ff',w,h)}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h*.55);sky.addColorStop(0,'#071023');sky.addColorStop(1,'#301143');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.48);const grass=ctx.createLinearGradient(0,h*.3,0,h);grass.addColorStop(0,'#123128');grass.addColorStop(1,'#071b18');ctx.fillStyle=grass;ctx.fillRect(0,h*.32,w,h*.68);drawRoad(w,h);drawFinish(w,h);drawWorldObjects(w,h);drawKart(w/2,h*.72,54,'#caff3d',true);if(player.hitFlash>0){ctx.fillStyle=`rgba(255,45,141,${player.hitFlash*.18})`;ctx.fillRect(0,0,w,h)}if(player.boundaryFlash>0){ctx.fillStyle=`rgba(33,230,255,${player.boundaryFlash*.12})`;ctx.fillRect(0,0,w,h);ctx.textAlign='center';ctx.font=`800 ${Math.max(18,w*.025)}px "Barlow Condensed",sans-serif`;ctx.fillStyle='#7cf4ff';ctx.fillText('OUTER BARRIER — TURN BACK',w/2,h*.58)}if(player.boost>0)drawBoostStatus(w,h);drawSurfaceStatus(w,h);drawMiniMap(w,h);drawParticles(w,h)}
function worldMapPoint(x,y,cx,cy,scale){return{x:cx+x*scale,y:cy+y*scale}}
function drawMiniMap(w,h){const size=Math.min(166,w*.19),mobile=w<720,x=w-size-18,y=mobile?h*.43:h-size-18,cx=x+size/2,cy=y+size/2,scale=size/2050;ctx.save();ctx.fillStyle='#07101ddd';ctx.strokeStyle='#526078';ctx.lineWidth=1;ctx.fillRect(x,y,size,size);ctx.strokeRect(x+.5,y+.5,size-1,size-1);ctx.fillStyle='#9ba8be';ctx.font='700 9px Inter, sans-serif';ctx.fillText('TRACK MAP',x+11,y+17);ctx.beginPath();trackSamples.forEach((p,i)=>{const m=worldMapPoint(p.x+p.rightX*p.width*ROAD_LIMIT,p.y+p.rightY*p.width*ROAD_LIMIT,cx,cy,scale);i?ctx.lineTo(m.x,m.y):ctx.moveTo(m.x,m.y)});for(let i=trackSamples.length-1;i>=0;i--){const p=trackSamples[i],m=worldMapPoint(p.x-p.rightX*p.width*ROAD_LIMIT,p.y-p.rightY*p.width*ROAD_LIMIT,cx,cy,scale);ctx.lineTo(m.x,m.y)}ctx.closePath();ctx.fillStyle='#111827';ctx.fill();ctx.strokeStyle='#73809a';ctx.lineWidth=1.5;ctx.stroke();ctx.beginPath();trackSamples.forEach((p,i)=>{const m=worldMapPoint(p.x,p.y,cx,cy,scale);i?ctx.lineTo(m.x,m.y):ctx.moveTo(m.x,m.y)});ctx.closePath();ctx.strokeStyle='#b4c0d5';ctx.lineWidth=1;ctx.stroke();boostPads.forEach(b=>{const m=worldMapPoint(b.x,b.y,cx,cy,scale);ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(m.x,m.y,size*.03,0,Math.PI*2);ctx.fill()});rivals.forEach(r=>{const m=worldMapPoint(r.x,r.y,cx,cy,scale);ctx.fillStyle=r.color;ctx.beginPath();ctx.arc(m.x,m.y,size*.025,0,Math.PI*2);ctx.fill()});const me=worldMapPoint(player.x,player.y,cx,cy,scale);ctx.translate(me.x,me.y);ctx.rotate(player.angle);ctx.fillStyle=player.onRoad?'#f7ffce':'#ffb45c';ctx.beginPath();ctx.moveTo(0,-size*.06);ctx.lineTo(-size*.035,size*.04);ctx.lineTo(size*.035,size*.04);ctx.closePath();ctx.fill();ctx.restore()}
function drawSurfaceStatus(w,h){ctx.save();ctx.textAlign='center';ctx.font=`800 ${Math.max(14,w*.018)}px "Barlow Condensed",sans-serif`;ctx.fillStyle=player.onRoad?'#caff3d':'#ffb45c';ctx.fillText(player.onRoad?'ON ROAD':'GRASS • SLOW',w/2,h*.64);ctx.restore()}function drawBoostStatus(w,h){ctx.save();ctx.textAlign='center';ctx.font=`italic 800 ${Math.max(16,w*.022)}px "Barlow Condensed",sans-serif`;ctx.fillStyle='#ff354d';ctx.shadowBlur=18;ctx.shadowColor='#ff354d';ctx.fillText('BOOST ACTIVE',w/2,h*.67);ctx.restore()}
function drawKart(x,y,s,c,hero){ctx.save();ctx.translate(x,y);if(hero&&Math.abs(player.speed)>20){const boosted=player.boost>0,flame=boosted?1.65:1,flameColor=boosted?'#ff354d':'#21e6ff99';ctx.fillStyle=flameColor;ctx.shadowBlur=boosted?24:0;ctx.shadowColor=flameColor;ctx.beginPath();ctx.moveTo(-s*.18,s*.35);ctx.lineTo(0,s*(.8+Math.random()*.35)*flame);ctx.lineTo(s*.18,s*.35);ctx.fill();if(boosted){ctx.fillStyle='#ffd35a';ctx.beginPath();ctx.moveTo(-s*.08,s*.35);ctx.lineTo(0,s*(.72+Math.random()*.18)*flame);ctx.lineTo(s*.08,s*.35);ctx.fill()}ctx.shadowBlur=0}ctx.shadowBlur=hero?22:8;ctx.shadowColor=c;ctx.fillStyle='#090b10';ctx.fillRect(-s*.55,-s*.05,s*.18,s*.55);ctx.fillRect(s*.37,-s*.05,s*.18,s*.55);ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(-s*.42,s*.32);ctx.lineTo(-s*.28,-s*.22);ctx.lineTo(0,-s*.42);ctx.lineTo(s*.28,-s*.22);ctx.lineTo(s*.42,s*.32);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#101724';ctx.fillRect(-s*.18,-s*.2,s*.36,s*.35);ctx.fillStyle='#fff';ctx.fillRect(-s*.06,-s*.06,s*.12,s*.12);ctx.restore()}
function drawParticles(w,h){const motion=Math.abs(player.speed)/210;ctx.strokeStyle='#dbe9ff44';ctx.lineWidth=1;for(let i=0;i<24;i++){const seed=(i*83+Math.floor(performance.now()*.04*motion))%997,x=(seed*17)%w,y=h*.35+(seed*11)%(h*.65);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-w/2)*.018*motion,y+10+30*motion);ctx.stroke()}}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;update(dt,now);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
