const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),keys={};
let state='menu',startAt=0,last=performance.now(),countValue=3,sound=true;
const touchInput={up:false,down:false,left:false,right:false};
let touchPointer=null,touchOrigin=null;
const touchPad=$('#touchPad');

// Course data lives in world space. Changing these points reshapes both views.
const trackPoints=[
  {x:0,y:-900,width:270},{x:430,y:-830,width:270},{x:760,y:-440,width:250},
  {x:740,y:80,width:245},{x:410,y:600,width:270},{x:-190,y:740,width:280},
  {x:-710,y:440,width:255},{x:-820,y:-170,width:250},{x:-520,y:-690,width:265},{x:-130,y:-970,width:275}
];
const ROAD_LIMIT=.8,OFFROAD_LIMIT=1.22,TRACK_SAMPLES=160,GRASS_CRAWL_SPEED=44;
const wrap=n=>((n%1)+1)%1,pointAt=i=>trackPoints[(i+trackPoints.length)%trackPoints.length];
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function catmull(a,b,c,d,t){const t2=t*t,t3=t2*t;return .5*((2*b)+(-a+c)*t+(2*a-5*b+4*c-d)*t2+(-a+3*b-3*c+d)*t3)}
function trackPosition(t){const n=trackPoints.length,u=wrap(t)*n,i=Math.floor(u),f=u-i,a=pointAt(i-1),b=pointAt(i),c=pointAt(i+1),d=pointAt(i+2);return{x:catmull(a.x,b.x,c.x,d.x,f),y:catmull(a.y,b.y,c.y,d.y,f),width:(b.width+(c.width-b.width)*f)*1.35}}
function sampleTrack(t){const p=trackPosition(t),a=trackPosition(t-.0008),b=trackPosition(t+.0008),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1;return{...p,t:wrap(t),dirX:dx/len,dirY:dy/len,rightX:-dy/len,rightY:dx/len,angle:Math.atan2(dx,-dy)}}
const trackSamples=Array.from({length:TRACK_SAMPLES},(_,i)=>sampleTrack(i/TRACK_SAMPLES));
function nearestTrack(x,y){let best;for(const p of trackSamples){const dx=x-p.x,dy=y-p.y,d2=dx*dx+dy*dy;if(!best||d2<best.d2)best={p,d2}}const distance=Math.sqrt(best.d2);return{...best,distance,onRoad:distance<=best.p.width*ROAD_LIMIT}}

// Simulation state is deliberately separate from screen and camera state.
const player={x:0,y:0,angle:0,speed:0,maxSpeed:205,reverseSpeed:68,acceleration:112,brakePower:240,friction:40,turnSpeed:2.9,steer:0,lap:1,trackT:.018,lastTrackT:.018,onRoad:true,boost:0,best:null,lapStart:0,hitFlash:0,boundaryFlash:0,collisionCooldown:0};
const camera={x:0,y:0,angle:0};
function snapCamera(){camera.x=player.x;camera.y=player.y;camera.angle=player.angle}
function setPlayerStart(){const p=sampleTrack(.018);Object.assign(player,{x:p.x,y:p.y,angle:p.angle,speed:0,steer:0,lap:1,trackT:p.t,lastTrackT:p.t,onRoad:true,boost:0,best:null,lapStart:0,hitFlash:0,boundaryFlash:0,collisionCooldown:0});snapCamera()}setPlayerStart();

// Objects remain world-coordinate records; image frames can replace the placeholder karts later.
const spriteCatalog={kart:{frames:['rear','rear-left','rear-right','side']}};
const boostPads=[.17,.47,.76].map((t,i)=>({...sampleTrack(t),t,radius:78,armed:true,color:i===1?'#ff8b35':'#ffe45c'}));
const obstacles=[.29,.58,.88].map((t,i)=>{const p=sampleTrack(t),side=i%2?-1.22:1.22;return{x:p.x+p.rightX*p.width*side,y:p.y+p.rightY*p.width*side,radius:34,color:i%2?'#ff2d8d':'#21e6ff'}});
const rivals=Array.from({length:5},(_,i)=>({t:.05+i*.105,lap:1,speed:122+i*7,x:0,y:0,angle:0,color:['#ff2d8d','#ffd83d','#21e6ff','#8e61ff','#ff713d'][i]}));
const scenery=Array.from({length:42},(_,i)=>{const p=sampleTrack(i/42+.013),side=i%2?1:-1,offset=p.width*(1.32+(i%4)*.18);return{x:p.x+p.rightX*offset*side,y:p.y+p.rightY*offset*side,size:45+(i%3)*19,color:side>0?'#21e6ff':'#ff2d8d'}});
function syncRival(r){const p=sampleTrack(r.t);r.x=p.x;r.y=p.y;r.angle=p.angle}rivals.forEach(syncRival);

function resize(){const d=Math.min(devicePixelRatio,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key.toLowerCase(),release=()=>keys[k]=false;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true;b.setPointerCapture(e.pointerId)});b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});
document.addEventListener('visibilitychange',()=>{if(document.hidden){Object.keys(keys).forEach(k=>keys[k]=false);resetTouchPad()}});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=`SOUND ${sound?'ON':'OFF'}`};
$('#startBtn').onclick=startRace;$('#restartBtn').onclick=startRace;$('#restartRaceBtn').onclick=startRace;
function beep(freq,d=.08){if(!sound)return;const a=beep.a||(beep.a=new AudioContext),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function startRace(){resetTouchPad();setPlayerStart();boostPads.forEach(b=>b.armed=true);rivals.forEach((r,i)=>{r.t=wrap(.06+i*.105);r.lap=1;syncRival(r)});$('#startScreen').classList.remove('show');$('#finishScreen').classList.remove('show');state='countdown';countValue=3;startAt=performance.now();showCount('3');beep(220)}
function showCount(t){const el=$('#countdown');el.textContent=t;el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop')}
function format(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,x=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}

function updatePlayer(dt){
  const up=keys.arrowup||keys.w||touchInput.up,down=keys.arrowdown||keys.s||touchInput.down,left=keys.arrowleft||keys.a||touchInput.left,right=keys.arrowright||keys.d;
  const wasOnRoad=player.onRoad,before=nearestTrack(player.x,player.y);player.onRoad=before.onRoad;
  if(up)player.speed+=player.acceleration*dt;else if(player.speed>0)player.speed-=player.friction*dt;else if(player.speed<0)player.speed+=player.friction*dt;
  if(down){if(player.speed>0)player.speed-=player.brakePower*dt;else player.speed-=player.acceleration*.72*dt}
  if(!player.onRoad&&player.speed>GRASS_CRAWL_SPEED)player.speed=Math.max(GRASS_CRAWL_SPEED,player.speed-260*dt);
  const surfaceMax=player.onRoad?player.maxSpeed:GRASS_CRAWL_SPEED,boostMax=player.onRoad&&player.boost>0?player.maxSpeed*1.28:surfaceMax;
  if(player.speed>boostMax)player.speed=Math.max(boostMax,player.speed-player.brakePower*dt);
  if(player.speed<-player.reverseSpeed)player.speed=-player.reverseSpeed;
  if(Math.abs(player.speed)<2&&!up&&!down)player.speed=0;
  const steerInput=(right?1:0)-(left?1:0),speedRatio=Math.min(1,Math.abs(player.speed)/player.maxSpeed);
  // High speed steering is intentionally less sharp than low speed steering.
  const turnScale=.96-speedRatio*.48;
  player.steer+=(steerInput-player.steer)*Math.min(1,dt*11);
  player.angle+=steerInput*player.turnSpeed*turnScale*dt*(player.speed>=0?1:-1);
  player.x+=Math.sin(player.angle)*player.speed*dt;player.y-=Math.cos(player.angle)*player.speed*dt;
  player.collisionCooldown=Math.max(0,player.collisionCooldown-dt);
  if(!player.collisionCooldown)for(const o of obstacles){const dx=player.x-o.x,dy=player.y-o.y,d=Math.hypot(dx,dy);if(d<o.radius+26){const nx=d?dx/d:-Math.sin(player.angle),ny=d?dy/d:Math.cos(player.angle);player.x=o.x+nx*(o.radius+27);player.y=o.y+ny*(o.radius+27);player.speed=-Math.max(24,Math.min(52,Math.abs(player.speed)*.22));player.collisionCooldown=.22;player.hitFlash=1;beep(105,.09);break}}
  let near=nearestTrack(player.x,player.y);
  if(near.distance>near.p.width*OFFROAD_LIMIT){const dx=player.x-near.p.x,dy=player.y-near.p.y,d=near.distance||1;player.x=near.p.x+dx/d*near.p.width*OFFROAD_LIMIT;player.y=near.p.y+dy/d*near.p.width*OFFROAD_LIMIT;player.speed=0;player.boundaryFlash=1;near=nearestTrack(player.x,player.y);beep(150,.07)}
  player.onRoad=near.onRoad;if(!wasOnRoad&&player.onRoad&&up)player.speed=Math.max(player.speed,82);player.trackT=near.p.t;
}
function updateWorld(dt,now){
  boostPads.forEach(b=>{const d=Math.hypot(player.x-b.x,player.y-b.y);if(d>b.radius*1.7)b.armed=true;if(d<b.radius&&b.armed){b.armed=false;player.boost=1.5;player.speed=Math.max(player.speed,player.maxSpeed*1.14);beep(880,.12)}});
  player.boost=Math.max(0,player.boost-dt);player.hitFlash=Math.max(0,player.hitFlash-dt*2.8);player.boundaryFlash=Math.max(0,player.boundaryFlash-dt*2.2);
  if(player.trackT<.12&&player.lastTrackT>.88&&player.speed>20&&player.onRoad){const lapTime=now-player.lapStart;player.best=player.best?Math.min(player.best,lapTime):lapTime;player.lapStart=now;if(player.lap>=3){finish(now);return}player.lap++}player.lastTrackT=player.trackT;
  rivals.forEach((r,i)=>{const old=r.t;r.speed=132+i*4+Math.sin(now/800+i)*7;r.t=wrap(r.t+r.speed*dt/6500);if(r.t<.12&&old>.88)r.lap++;syncRival(r)});
}
function updateCamera(dt){const follow=Math.min(1,dt*10),angleFollow=Math.min(1,dt*8);camera.x+=(player.x-camera.x)*follow;camera.y+=(player.y-camera.y)*follow;camera.angle+=angleDiff(player.angle,camera.angle)*angleFollow}
function updateHud(now){const meScore=(player.lap-1)+player.trackT,ahead=rivals.filter(r=>(r.lap-1)+r.t>meScore).length;$('#position').textContent=Math.min(6,ahead+1);$('#lap').textContent=player.lap;$('#speed').textContent=String(Math.round(Math.abs(player.speed))).padStart(3,'0');$('#raceTime').textContent=format(now-startAt);$('#bestLap').textContent=player.best?format(player.best):'--:--.---'}
function update(dt,now){if(state==='countdown'){const elapsed=(now-startAt)/1000,newCount=3-Math.floor(elapsed);if(newCount!==countValue&&newCount>0){countValue=newCount;showCount(String(newCount));beep(260+(3-newCount)*110)}if(elapsed>=3){showCount('GO!');beep(660,.16);state='race';startAt=now;player.lapStart=now}updateCamera(dt);return}if(state!=='race')return;updatePlayer(dt);updateWorld(dt,now);updateCamera(dt);updateHud(now)}
function finish(now){state='finish';const pos=$('#position').textContent,suffix=pos==='1'?'ST':pos==='2'?'ND':pos==='3'?'RD':'TH';$('#finishPlace').textContent=pos+suffix;$('#finalTime').textContent=format(now-startAt);setTimeout(()=>$('#finishScreen').classList.add('show'),400);beep(520,.25)}

function canvasPoint(x,y){const r=canvas.getBoundingClientRect();return{x:x-r.left,y:y-r.top}}
function resetTouchPad(){touchPointer=null;touchOrigin=null;Object.keys(touchInput).forEach(k=>touchInput[k]=false);touchPad.classList.remove('show');touchPad.style.setProperty('--stick-x','0px');touchPad.style.setProperty('--stick-y','0px')}
function updateTouchDrive(x,y){if(!touchOrigin)return;let dx=x-touchOrigin.x,dy=y-touchOrigin.y,len=Math.hypot(dx,dy);if(len>52){dx=dx/len*52;dy=dy/len*52}touchInput.left=dx<-10;touchInput.right=dx>10;touchInput.up=dy<-10;touchInput.down=dy>10;touchPad.style.setProperty('--stick-x',`${dx}px`);touchPad.style.setProperty('--stick-y',`${dy}px`)}
function beginTouch(id,x,y){if(touchPointer!==null||(state!=='race'&&state!=='countdown'))return false;touchPointer=id;touchOrigin={x,y};touchPad.style.left=`${x}px`;touchPad.style.top=`${y}px`;touchPad.classList.add('show');updateTouchDrive(x,y);return true}
function moveTouch(id,x,y){if(touchPointer!==id)return false;updateTouchDrive(x,y);return true}function endTouch(id){if(touchPointer===id)resetTouchPad()}
if(window.PointerEvent){canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const p=canvasPoint(e.clientX,e.clientY);if(beginTouch(e.pointerId,p.x,p.y)){e.preventDefault();canvas.setPointerCapture?.(e.pointerId)}});canvas.addEventListener('pointermove',e=>{const p=canvasPoint(e.clientX,e.clientY);if(moveTouch(e.pointerId,p.x,p.y))e.preventDefault()});canvas.addEventListener('pointerup',e=>endTouch(e.pointerId));canvas.addEventListener('pointercancel',e=>endTouch(e.pointerId));canvas.addEventListener('lostpointercapture',e=>endTouch(e.pointerId))}

// Converts world points to the upper-screen pseudo-3D camera. The player stays fixed on screen.
function cameraPoint(x,y,w,raceH){const dx=x-camera.x,dy=y-camera.y,s=Math.sin(camera.angle),c=Math.cos(camera.angle),depth=dx*s-dy*c,side=dx*c+dy*s;if(depth<68||depth>2300)return null;const scale=(320*Math.max(.72,raceH/500))/depth,horizon=raceH*.43;return{x:w/2+side*scale,y:horizon+160*scale,depth,scale}}
function roadQuad(a,b,w,raceH){const ar={x:a.x+a.rightX*a.width,y:a.y+a.rightY*a.width},al={x:a.x-a.rightX*a.width,y:a.y-a.rightY*a.width},br={x:b.x+b.rightX*b.width,y:b.y+b.rightY*b.width},bl={x:b.x-b.rightX*b.width,y:b.y-b.rightY*b.width},q=[cameraPoint(ar.x,ar.y,w,raceH),cameraPoint(al.x,al.y,w,raceH),cameraPoint(br.x,br.y,w,raceH),cameraPoint(bl.x,bl.y,w,raceH)];return q.some(v=>!v)?null:q}
function polygon(points,color){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=color;ctx.fill()}
function renderGround(w,raceH){const cell=800,range=3,startX=Math.floor(camera.x/cell)-range,startY=Math.floor(camera.y/cell)-range,tiles=[];for(let gy=startY;gy<=startY+range*2;gy++)for(let gx=startX;gx<=startX+range*2;gx++){const x=gx*cell,y=gy*cell,q=[cameraPoint(x,y,w,raceH),cameraPoint(x+cell,y,w,raceH),cameraPoint(x+cell,y+cell,w,raceH),cameraPoint(x,y+cell,w,raceH)];if(!q.some(v=>!v))tiles.push({q,depth:q.reduce((n,p)=>n+p.depth,0)/4,gx,gy})}tiles.sort((a,b)=>b.depth-a.depth);for(const tile of tiles){const shade=(tile.gx*19+tile.gy*31)&3;polygon(tile.q,['#287354','#317f5c','#2d7957','#3a8963'][shade])}}
function renderRoad(w,raceH){const quads=[];for(let i=0;i<trackSamples.length;i++){const q=roadQuad(trackSamples[i],trackSamples[(i+1)%trackSamples.length],w,raceH);if(q)quads.push({q,depth:q.reduce((n,p)=>n+p.depth,0)/4,i})}quads.sort((a,b)=>b.depth-a.depth);for(const item of quads){const q=item.q;polygon(q,item.i%6<3?'#424751':'#373c46');if(item.i%2===0){ctx.strokeStyle='#f5edcf44';ctx.lineWidth=Math.max(1,3*q[0].scale);ctx.beginPath();ctx.moveTo(q[0].x,q[0].y);ctx.lineTo(q[2].x,q[2].y);ctx.moveTo(q[1].x,q[1].y);ctx.lineTo(q[3].x,q[3].y);ctx.stroke()}if(item.i%10<3){ctx.strokeStyle='#fff8dc35';ctx.beginPath();ctx.moveTo((q[0].x+q[1].x)*.5,(q[0].y+q[1].y)*.5);ctx.lineTo((q[2].x+q[3].x)*.5,(q[2].y+q[3].y)*.5);ctx.stroke()}}}
function drawRibbon(p,width,length,color,w,raceH){const rx=p.rightX*width,ry=p.rightY*width,fx=p.dirX*length,fy=p.dirY*length,q=[cameraPoint(p.x-rx-fx,p.y-ry-fy,w,raceH),cameraPoint(p.x+rx-fx,p.y+ry-fy,w,raceH),cameraPoint(p.x+rx+fx,p.y+ry+fy,w,raceH),cameraPoint(p.x-rx+fx,p.y-ry+fy,w,raceH)];if(!q.some(v=>!v))polygon(q,color)}
function spriteFrameFor(angle){const relative=Math.abs(angleDiff(angle,camera.angle));return relative<.45?spriteCatalog.kart.frames[0]:relative<1.25?(angleDiff(angle,camera.angle)>0?spriteCatalog.kart.frames[1]:spriteCatalog.kart.frames[2]):spriteCatalog.kart.frames[3]}
function renderObjects(w,raceH){const visible=[];for(const b of boostPads){const p=cameraPoint(b.x,b.y,w,raceH);if(p)visible.push({type:'boost',p,item:b})}for(const o of obstacles){const p=cameraPoint(o.x,o.y,w,raceH);if(p)visible.push({type:'obstacle',p,item:o})}for(const r of rivals){const p=cameraPoint(r.x,r.y,w,raceH);if(p)visible.push({type:'rival',p,item:r})}for(const t of scenery){const p=cameraPoint(t.x,t.y,w,raceH);if(p)visible.push({type:'tree',p,item:t})}visible.sort((a,b)=>b.p.depth-a.p.depth);for(const v of visible){const p=v.p,it=v.item;if(v.type==='boost')drawRibbon(it,it.width*.78,20,it.color,w,raceH);else if(v.type==='tree'){const s=Math.min(150,it.size*p.scale);ctx.fillStyle='#25452d';ctx.fillRect(p.x-s*.11,p.y-s*.72,s*.22,s*.72);ctx.fillStyle=it.color+'77';ctx.shadowBlur=16;ctx.shadowColor=it.color;ctx.beginPath();ctx.moveTo(p.x,p.y-s*1.55);ctx.lineTo(p.x-s*.55,p.y-s*.48);ctx.lineTo(p.x+s*.55,p.y-s*.48);ctx.closePath();ctx.fill();ctx.shadowBlur=0}else if(v.type==='obstacle'){const s=Math.min(95,it.radius*p.scale);ctx.fillStyle='#101522';ctx.fillRect(p.x-s,p.y-s*.85,s*2,s*.85);ctx.fillStyle=it.color;ctx.shadowBlur=15;ctx.shadowColor=it.color;ctx.fillRect(p.x-s*.88,p.y-s*.72,s*1.76,s*.15);ctx.shadowBlur=0}else drawKart(p.x,p.y,Math.min(76,28*p.scale),it.color,false,0,spriteFrameFor(it.angle))}}
function renderFinish(w,raceH){const p=sampleTrack(0);drawRibbon(p,p.width,9,'#f4f6ff',w,raceH)}
function drawKart(x,y,s,color,hero,tilt=0,frame='rear'){ctx.save();ctx.translate(x,y);ctx.rotate(tilt);if(hero&&Math.abs(player.speed)>20){const boosted=player.boost>0,flame=boosted?1.65:1,flameColor=boosted?'#ff354d':'#21e6ff99';ctx.fillStyle=flameColor;ctx.shadowBlur=boosted?24:0;ctx.shadowColor=flameColor;ctx.beginPath();ctx.moveTo(-s*.18,s*.35);ctx.lineTo(0,s*(.8+Math.random()*.35)*flame);ctx.lineTo(s*.18,s*.35);ctx.fill();if(boosted){ctx.fillStyle='#ffd35a';ctx.beginPath();ctx.moveTo(-s*.08,s*.35);ctx.lineTo(0,s*(.72+Math.random()*.18)*flame);ctx.lineTo(s*.08,s*.35);ctx.fill()}ctx.shadowBlur=0}ctx.shadowBlur=hero?22:8;ctx.shadowColor=color;ctx.fillStyle='#090b10';ctx.fillRect(-s*.55,-s*.05,s*.18,s*.55);ctx.fillRect(s*.37,-s*.05,s*.18,s*.55);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(-s*.42,s*.32);ctx.lineTo(-s*.28,-s*.22);ctx.lineTo(0,-s*.42);ctx.lineTo(s*.28,-s*.22);ctx.lineTo(s*.42,s*.32);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle=frame==='side'?'#263346':'#101724';ctx.fillRect(-s*.18,-s*.2,s*.36,s*.35);ctx.fillStyle='#fff';ctx.fillRect(-s*.06,-s*.06,s*.12,s*.12);ctx.restore()}
function renderParticles(w,raceH){const motion=Math.abs(player.speed)/210;ctx.strokeStyle='#dbe9ff44';ctx.lineWidth=1;for(let i=0;i<18;i++){const seed=(i*83+Math.floor(performance.now()*.04*motion))%997,x=(seed*17)%w,y=raceH*.48+(seed*11)%(raceH*.52);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-w/2)*.018*motion,y+8+24*motion);ctx.stroke()}}
function renderRaceView(w,raceH){ctx.save();ctx.beginPath();ctx.rect(0,0,w,raceH);ctx.clip();const sky=ctx.createLinearGradient(0,0,0,raceH*.48);sky.addColorStop(0,'#5e8dd7');sky.addColorStop(1,'#b77fb1');ctx.fillStyle=sky;ctx.fillRect(0,0,w,raceH*.48);const grass=ctx.createLinearGradient(0,raceH*.35,0,raceH);grass.addColorStop(0,'#3b9a6c');grass.addColorStop(1,'#195d43');ctx.fillStyle=grass;ctx.fillRect(0,raceH*.38,w,raceH*.62);renderGround(w,raceH);renderRoad(w,raceH);renderFinish(w,raceH);renderObjects(w,raceH);drawKart(w/2,raceH*.78,Math.min(58,raceH*.115),'#caff3d',true,player.steer*.14);if(player.hitFlash>0){ctx.fillStyle=`rgba(255,45,141,${player.hitFlash*.18})`;ctx.fillRect(0,0,w,raceH)}if(player.boundaryFlash>0){ctx.fillStyle=`rgba(33,230,255,${player.boundaryFlash*.12})`;ctx.fillRect(0,0,w,raceH);ctx.textAlign='center';ctx.font=`800 ${Math.max(16,w*.02)}px "Barlow Condensed",sans-serif`;ctx.fillStyle='#e2feff';ctx.fillText('OUTER BARRIER — TURN BACK',w/2,raceH*.7)}ctx.textAlign='center';ctx.font=`800 ${Math.max(14,w*.018)}px "Barlow Condensed",sans-serif`;ctx.fillStyle=player.onRoad?'#d9ff53':'#ffca75';ctx.fillText(player.onRoad?'ON ROAD':'GRASS • SLOW',w/2,raceH*.68);if(player.boost>0){ctx.font=`italic 800 ${Math.max(16,w*.022)}px "Barlow Condensed",sans-serif`;ctx.fillStyle='#ff354d';ctx.shadowBlur=18;ctx.shadowColor='#ff354d';ctx.fillText('BOOST ACTIVE',w/2,raceH*.61);ctx.shadowBlur=0}renderParticles(w,raceH);ctx.restore()}
function worldMapPoint(x,y,cx,cy,scale){return{x:cx+x*scale,y:cy+y*scale}}
function renderMinimap(w,h,raceH){const gap=8,pad=12,x=pad,y=raceH+gap,mapW=w-pad*2,mapH=h-y-pad,cx=x+mapW/2,cy=y+mapH/2+10,scale=Math.min((mapW-48)/2100,(mapH-42)/2000);ctx.fillStyle='#091323';ctx.fillRect(0,raceH,w,h-raceH);ctx.fillStyle='#101b2d';ctx.fillRect(x,y,mapW,mapH);ctx.strokeStyle='#79d6ee88';ctx.lineWidth=1;ctx.strokeRect(x+.5,y+.5,mapW-1,mapH-1);ctx.fillStyle='#9cecff';ctx.font='800 10px Inter,sans-serif';ctx.fillText('WORLD MAP  •  LIVE PLAYER COORDINATES',x+14,y+18);ctx.beginPath();trackSamples.forEach((p,i)=>{const m=worldMapPoint(p.x+p.rightX*p.width*ROAD_LIMIT,p.y+p.rightY*p.width*ROAD_LIMIT,cx,cy,scale);i?ctx.lineTo(m.x,m.y):ctx.moveTo(m.x,m.y)});for(let i=trackSamples.length-1;i>=0;i--){const p=trackSamples[i],m=worldMapPoint(p.x-p.rightX*p.width*ROAD_LIMIT,p.y-p.rightY*p.width*ROAD_LIMIT,cx,cy,scale);ctx.lineTo(m.x,m.y)}ctx.closePath();ctx.fillStyle='#343943';ctx.fill();ctx.strokeStyle='#f6efcf';ctx.lineWidth=1.2;ctx.stroke();ctx.beginPath();trackSamples.forEach((p,i)=>{const m=worldMapPoint(p.x,p.y,cx,cy,scale);i?ctx.lineTo(m.x,m.y):ctx.moveTo(m.x,m.y)});ctx.closePath();ctx.strokeStyle='#fef8dd88';ctx.stroke();boostPads.forEach(b=>{const m=worldMapPoint(b.x,b.y,cx,cy,scale);ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(m.x,m.y,4,0,Math.PI*2);ctx.fill()});rivals.forEach(r=>{const m=worldMapPoint(r.x,r.y,cx,cy,scale);ctx.fillStyle=r.color;ctx.beginPath();ctx.arc(m.x,m.y,3.5,0,Math.PI*2);ctx.fill()});const me=worldMapPoint(player.x,player.y,cx,cy,scale);ctx.save();ctx.translate(me.x,me.y);ctx.rotate(player.angle);ctx.fillStyle=player.onRoad?'#f7ffce':'#ffb45c';ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(-6,7);ctx.lineTo(6,7);ctx.closePath();ctx.fill();ctx.restore();ctx.fillStyle='#b7c4d9';ctx.font='700 9px Inter,sans-serif';ctx.fillText(`X ${Math.round(player.x)}  Y ${Math.round(player.y)}  A ${Math.round(player.angle*180/Math.PI)}°`,x+14,y+mapH-12)}
function render(){const w=canvas.clientWidth,h=canvas.clientHeight,raceH=Math.floor(h*.64);ctx.clearRect(0,0,w,h);renderRaceView(w,raceH);renderMinimap(w,h,raceH)}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;update(dt,now);render();requestAnimationFrame(loop)}requestAnimationFrame(loop);
