const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s); const keys={};
let state='menu',startAt=0,last=performance.now(),countValue=3,sound=true;
const player={angle:0,speed:0,lateral:0,lap:1,progress:0,distance:0,best:null,lapStart:0,boost:0,wallHit:false,wallFlash:0};
const rivals=Array.from({length:5},(_,i)=>({distance:.04+i*.105,progress:.04+i*.105,speed:118+i*7,lane:(i%3-1)*.26,color:['#ff2d8d','#ffd83d','#21e6ff','#8e61ff','#ff713d'][i]}));
const trackLength=3250,courseCenters=[0,0,.05,.62,.76,.2,-.48,-.72,-.15,.46,.6,.16],boosts=[.17,.48,.79],boostArmed=boosts.map(()=>true),touchInput={up:false,down:false,left:false,right:false};let touchPointer=null,touchOrigin=null;const touchPad=$('#touchPad');
function resize(){const d=Math.min(devicePixelRatio,2),r=canvas.getBoundingClientRect();canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys[e.key.toLowerCase()]=true});
addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key.toLowerCase(),release=()=>keys[k]=false;b.addEventListener('pointerdown',e=>{e.preventDefault();keys[k]=true;b.setPointerCapture(e.pointerId)});b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release)});document.addEventListener('visibilitychange',()=>{if(document.hidden){Object.keys(keys).forEach(k=>keys[k]=false);resetTouchPad()}});
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=`SOUND ${sound?'ON':'OFF'}`};
$('#startBtn').onclick=startRace;$('#restartBtn').onclick=startRace;$('#restartRaceBtn').onclick=startRace;
function beep(freq,d=.08){if(!sound)return;const a=beep.a||(beep.a=new AudioContext),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type='square';g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function startRace(){resetTouchPad();Object.assign(player,{speed:0,lateral:0,lap:1,progress:0,distance:0,best:null,lapStart:0,boost:0,wallHit:false,wallFlash:0});boostArmed.fill(true);rivals.forEach((r,i)=>{r.distance=.04+i*.105;r.progress=r.distance});$('#startScreen').classList.remove('show');$('#finishScreen').classList.remove('show');state='countdown';countValue=3;startAt=performance.now();showCount('3');beep(220)}
function showCount(t){const el=$('#countdown');el.textContent=t;el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop')}
function format(ms){const m=Math.floor(ms/60000),s=Math.floor(ms/1000)%60,x=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}
function update(dt,now){
 if(state==='countdown'){const elapsed=(now-startAt)/1000,newCount=3-Math.floor(elapsed);if(newCount!==countValue&&newCount>0){countValue=newCount;showCount(String(newCount));beep(260+(3-newCount)*110)}if(elapsed>=3){showCount('GO!');beep(660,.16);state='race';startAt=now;player.lapStart=now}return}
 if(state!=='race')return;
 const up=keys.arrowup||keys.w||touchInput.up,down=keys.arrowdown||keys.s||touchInput.down,left=keys.arrowleft||keys.a||touchInput.left,right=keys.arrowright||keys.d||touchInput.right;
 if(up)player.speed+=105*dt;else player.speed-=37*dt;if(down)player.speed-=150*dt;
 const steer=(right?1:0)-(left?1:0),curveForce=Math.max(-3,Math.min(3,courseBend(player.progress)));player.lateral+=steer*dt*(.7+player.speed/180);player.lateral-=curveForce*(player.speed/205)*.36*dt;player.lateral*=Math.pow(.93,dt*60);
 const wallLimit=.72,hitWall=Math.abs(player.lateral)>wallLimit;if(hitWall){player.lateral=Math.sign(player.lateral)*wallLimit;player.boost=0;if(!player.wallHit){player.speed=Math.min(78,player.speed*.42);player.wallHit=true;player.wallFlash=1;beep(120,.07)}player.speed-=260*dt}else player.wallHit=false;player.speed=Math.max(0,Math.min(player.boost>0?250:205,player.speed));player.boost=Math.max(0,player.boost-dt);player.wallFlash=Math.max(0,player.wallFlash-dt*3);
 const distanceDelta=player.speed*dt/trackLength,prev=player.progress;player.distance+=distanceDelta;player.progress=player.distance%1;
 boosts.forEach((b,i)=>{let d=Math.abs(player.progress-b);if(d>.5)d=1-d;if(d>.04){boostArmed[i]=true;return}if(d<.028&&Math.abs(player.lateral)<.52&&boostArmed[i]){boostArmed[i]=false;player.boost=1.5;player.speed=Math.max(player.speed,230);beep(880,.12)}});
 if(player.progress<prev){const lapTime=now-player.lapStart;player.best=player.best?Math.min(player.best,lapTime):lapTime;player.lapStart=now;if(player.lap>=3){finish(now);return}player.lap++}
 rivals.forEach((r,i)=>{r.speed=132+i*4+Math.sin(now/800+i)*7;r.distance+=r.speed*dt/trackLength;r.progress=r.distance%1});
 const ahead=rivals.filter(r=>r.distance>player.distance).length;$('#position').textContent=Math.min(6,ahead+1);$('#lap').textContent=player.lap;$('#speed').textContent=String(Math.round(player.speed)).padStart(3,'0');$('#raceTime').textContent=format(now-startAt);$('#bestLap').textContent=player.best?format(player.best):'--:--.---';
}
function finish(now){state='finish';const pos=$('#position').textContent,suffix=pos==='1'?'ST':pos==='2'?'ND':pos==='3'?'RD':'TH';$('#finishPlace').textContent=pos+suffix;$('#finalTime').textContent=format(now-startAt);setTimeout(()=>$('#finishScreen').classList.add('show'),400);beep(520,.25)}
function canvasPoint(x,y){const r=canvas.getBoundingClientRect();return{x:x-r.left,y:y-r.top}}
function resetTouchPad(){touchPointer=null;touchOrigin=null;Object.keys(touchInput).forEach(k=>touchInput[k]=false);touchPad.classList.remove('show');touchPad.style.setProperty('--stick-x','0px');touchPad.style.setProperty('--stick-y','0px')}
function updateTouchDrive(x,y){if(!touchOrigin)return;let dx=x-touchOrigin.x,dy=y-touchOrigin.y,len=Math.hypot(dx,dy);if(len>52){dx=dx/len*52;dy=dy/len*52}touchInput.left=dx<-10;touchInput.right=dx>10;touchInput.up=dy<-10;touchInput.down=dy>10;touchPad.style.setProperty('--stick-x',`${dx}px`);touchPad.style.setProperty('--stick-y',`${dy}px`)}
function beginTouch(id,x,y){if(touchPointer!==null||(state!=='race'&&state!=='countdown'))return false;touchPointer=id;touchOrigin={x,y};touchPad.style.left=`${x}px`;touchPad.style.top=`${y}px`;touchPad.classList.add('show');updateTouchDrive(x,y);return true}
function moveTouch(id,x,y){if(touchPointer!==id)return false;updateTouchDrive(x,y);return true}
function endTouch(id){if(touchPointer===id)resetTouchPad()}
if(window.PointerEvent){canvas.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'&&e.pointerType!=='pen')return;const p=canvasPoint(e.clientX,e.clientY);if(beginTouch(e.pointerId,p.x,p.y)){e.preventDefault();canvas.setPointerCapture?.(e.pointerId)}});canvas.addEventListener('pointermove',e=>{const p=canvasPoint(e.clientX,e.clientY);if(moveTouch(e.pointerId,p.x,p.y))e.preventDefault()});canvas.addEventListener('pointerup',e=>endTouch(e.pointerId));canvas.addEventListener('pointercancel',e=>endTouch(e.pointerId));canvas.addEventListener('lostpointercapture',e=>endTouch(e.pointerId))}else{const findTouch=(list,id)=>Array.from(list).find(t=>t.identifier===id);canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0],p=canvasPoint(t.clientX,t.clientY);if(beginTouch(t.identifier,p.x,p.y))e.preventDefault()},{passive:false});canvas.addEventListener('touchmove',e=>{const t=findTouch(e.changedTouches,touchPointer);if(t){const p=canvasPoint(t.clientX,t.clientY);if(moveTouch(t.identifier,p.x,p.y))e.preventDefault()}},{passive:false});canvas.addEventListener('touchend',e=>{const t=findTouch(e.changedTouches,touchPointer);if(t)endTouch(t.identifier)});canvas.addEventListener('touchcancel',()=>resetTouchPad())}
function courseCenter(progress){const p=((progress%1)+1)%1,n=courseCenters.length,scaled=p*n,index=Math.floor(scaled),t=scaled-index,ease=t*t*(3-2*t),a=courseCenters[index],b=courseCenters[(index+1)%n];return a+(b-a)*ease}
function courseBend(progress){const step=.003;return(courseCenter(progress+step)-courseCenter(progress-step))/(step*2)}
function roadHalf(t,w){return w*(.045+.43*t)}
function roadX(y,w,h){const horizon=h*.34,t=(y-horizon)/(h-horizon),lookAhead=(1-t)*.28,curve=(courseCenter(player.progress+lookAhead)-courseCenter(player.progress))*w*.62;return w/2+curve-player.lateral*w*.34*t}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);
 const g=ctx.createLinearGradient(0,0,0,h*.55);g.addColorStop(0,'#071023');g.addColorStop(1,'#301143');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
 // skyline
 const block=w/35,cityStep=Math.floor(player.distance*190/block),cityDrift=(player.distance*190+player.lateral*w*.08)%block;ctx.fillStyle='#080c18';for(let i=-2;i<38;i++){const id=i+cityStep,x=i*block-cityDrift,bh=18+((id*37)%90);ctx.fillRect(x,h*.34-bh,block+2,bh);if(id%2===0){ctx.fillStyle=id%4?'#21e6ff55':'#ff2d8d55';ctx.fillRect(x+4,h*.34-bh+8,2,Math.max(4,bh-15));ctx.fillStyle='#080c18'}}
 ctx.fillStyle='#101526';ctx.fillRect(0,h*.34,w,h*.66);
 const slices=70,hz=h*.34;for(let i=0;i<slices;i++){const t=i/slices,t2=(i+1)/slices,y=hz+(h-hz)*t,y2=hz+(h-hz)*t2,half=roadHalf(t,w),half2=roadHalf(t2,w),x=roadX(y,w,h),x2=roadX(y2,w,h);ctx.beginPath();ctx.moveTo(x-half,y);ctx.lineTo(x+half,y);ctx.lineTo(x2+half2,y2);ctx.lineTo(x2-half2,y2);ctx.fillStyle=(i+Math.floor(player.progress*800))%8<4?'#252a35':'#20242e';ctx.fill();if(i%7<3){ctx.strokeStyle='#dce6ff44';ctx.lineWidth=Math.max(1,8*t);for(const lane of [-.34,.34]){ctx.beginPath();ctx.moveTo(x+half*lane,y);ctx.lineTo(x2+half2*lane,y2);ctx.stroke()}}}
 // neon edges
 for(const side of [-1,1]){ctx.beginPath();for(let i=0;i<=30;i++){const t=i/30,y=hz+(h-hz)*t,half=roadHalf(t,w),x=roadX(y,w,h)+half*side;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=side<0?'#ff2d8d':'#21e6ff';ctx.lineWidth=4;ctx.shadowBlur=18;ctx.shadowColor=ctx.strokeStyle;ctx.stroke();ctx.shadowBlur=0}
 for(const side of [-1,1])for(let i=0;i<11;i++){const t=(i/11+player.distance*4)%1;if(t<.06)continue;const y=hz+(h-hz)*t,half=roadHalf(t,w),x=roadX(y,w,h)+half*side*1.08,size=3+10*t;ctx.fillStyle=side<0?'#ff2d8d':'#21e6ff';ctx.shadowBlur=12;ctx.shadowColor=ctx.fillStyle;ctx.fillRect(x-size/2,y-size*2,size,size*2);ctx.shadowBlur=0}
 const nextTurn=courseBend(player.progress+.1);if(Math.abs(nextTurn)>1.1){ctx.save();ctx.textAlign='center';ctx.font=`800 ${Math.max(20,w*.035)}px "Barlow Condensed",sans-serif`;ctx.fillStyle='#ffe45c';ctx.shadowBlur=14;ctx.shadowColor='#ffe45c';ctx.fillText(nextTurn>0?'›››':'‹‹‹',w/2,h*.43);ctx.restore()}
 // finish line
 const finishD=(1-player.progress)%1;if(finishD<.22){const t=1-Math.pow(finishD/.22,.55),y=hz+(h-hz)*t,half=roadHalf(t,w),x=roadX(y,w,h),lineH=6+18*t,cols=12;for(let row=0;row<2;row++)for(let col=0;col<cols;col++){ctx.fillStyle=(row+col)%2?'#f5f7ff':'#10131d';ctx.fillRect(x-half+col*(half*2/cols),y-lineH/2+row*(lineH/2),half*2/cols+1,lineH/2+1)}}
 // boost pads
 boosts.forEach(b=>{let d=(b-player.progress+1)%1;if(d<.22){const t=1-Math.pow(d/.22,.55),y=hz+(h-hz)*t,x=roadX(y,w,h),ww=roadHalf(t,w)*.92,hh=8+17*t,color='#ffe45c';ctx.fillStyle='#111321';ctx.fillRect(x-ww/2-3,y-hh/2-3,ww+6,hh+6);ctx.fillStyle=color;ctx.shadowBlur=22;ctx.shadowColor=color;ctx.fillRect(x-ww/2,y-hh/2,ww,hh);ctx.fillStyle='#ffffff';for(let stripe=-.38;stripe<=.38;stripe+=.38)ctx.fillRect(x+ww*stripe-ww*.055,y-hh/2,ww*.11,hh);ctx.shadowBlur=0}});
 // rivals
 rivals.forEach(r=>{let d=(r.progress-player.progress+1)%1;if(d>.015&&d<.32){const t=1-Math.pow(d/.32,.55),y=hz+(h-hz)*t,half=roadHalf(t,w),x=roadX(y,w,h)+half*r.lane,sz=10+38*t;drawKart(x,y,sz,r.color,false)}});
 drawKart(w/2,h*.69,52,'#caff3d',true);if(player.wallFlash>0){ctx.fillStyle=`rgba(255,45,141,${player.wallFlash*.14})`;ctx.fillRect(0,0,w,h)}if(player.boost>0)drawBoostStatus(w,h);drawMiniMap(w,h);drawParticles(w,h);
}
function trackPoint(progress,cx,cy,scale){const a=progress*Math.PI*2-Math.PI/2,r=1+.13*Math.sin(a*3)-.07*Math.cos(a*2);return{x:cx+Math.cos(a)*scale*r,y:cy+Math.sin(a)*scale*.62*r}}
function drawMiniMap(w,h){
 const size=Math.min(166,w*.19),mobile=w<720,x=w-size-18,y=mobile?h*.43:h-size-18,cx=x+size/2,cy=y+size/2;
 ctx.save();
 ctx.fillStyle='#07101ddd';ctx.strokeStyle='#526078';ctx.lineWidth=1;ctx.fillRect(x,y,size,size);ctx.strokeRect(x+.5,y+.5,size-1,size-1);
 ctx.fillStyle='#9ba8be';ctx.font='700 9px Inter, sans-serif';ctx.letterSpacing='1px';ctx.fillText('TRACK MAP',x+11,y+17);
 ctx.beginPath();for(let i=0;i<=96;i++){const p=trackPoint(i/96,cx,cy,size*.34);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.closePath();ctx.strokeStyle='#111827';ctx.lineWidth=size*.115;ctx.stroke();
 ctx.beginPath();for(let i=0;i<=96;i++){const p=trackPoint(i/96,cx,cy,size*.34);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y)}ctx.closePath();ctx.strokeStyle='#73809a';ctx.lineWidth=size*.037;ctx.stroke();
 const boostColor='#ffe45c';boosts.forEach(p=>{const b=trackPoint(p,cx,cy,size*.34);ctx.fillStyle=boostColor;ctx.shadowBlur=10;ctx.shadowColor=boostColor;ctx.beginPath();ctx.arc(b.x,b.y,size*.032,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});
 rivals.forEach(r=>{const k=trackPoint(r.progress,cx,cy,size*.34);ctx.fillStyle=r.color;ctx.beginPath();ctx.arc(k.x,k.y,size*.027,0,Math.PI*2);ctx.fill()});
 const me=trackPoint(player.progress,cx,cy,size*.34),ahead=trackPoint((player.progress+.012)%1,cx,cy,size*.34),angle=Math.atan2(ahead.y-me.y,ahead.x-me.x),playerColor='#f7ffce';ctx.translate(me.x,me.y);ctx.rotate(angle);ctx.fillStyle=playerColor;ctx.shadowBlur=12;ctx.shadowColor=playerColor;ctx.beginPath();ctx.moveTo(size*.06,0);ctx.lineTo(-size*.037,-size*.035);ctx.lineTo(-size*.02,0);ctx.lineTo(-size*.037,size*.035);ctx.closePath();ctx.fill();ctx.shadowBlur=0;
 ctx.restore();
}
function drawBoostStatus(w,h){ctx.save();ctx.textAlign='center';ctx.font=`italic 800 ${Math.max(16,w*.022)}px "Barlow Condensed", sans-serif`;ctx.fillStyle='#ff354d';ctx.shadowBlur=18;ctx.shadowColor='#ff354d';ctx.fillText('BOOST ACTIVE',w/2,h*.64);ctx.restore()}
function drawKart(x,y,s,c,hero){ctx.save();ctx.translate(x,y);if(hero&&player.speed>20){const boosted=player.boost>0,flame=boosted?1.65:1,flameColor=boosted?'#ff354d':'#21e6ff99';ctx.fillStyle=flameColor;ctx.shadowBlur=boosted?24:0;ctx.shadowColor=flameColor;ctx.beginPath();ctx.moveTo(-s*.18,s*.35);ctx.lineTo(0,s*(.8+Math.random()*.35)*flame);ctx.lineTo(s*.18,s*.35);ctx.fill();if(boosted){ctx.fillStyle='#ffd35a';ctx.beginPath();ctx.moveTo(-s*.08,s*.35);ctx.lineTo(0,s*(.72+Math.random()*.18)*flame);ctx.lineTo(s*.08,s*.35);ctx.fill()}ctx.shadowBlur=0}ctx.shadowBlur=hero?22:8;ctx.shadowColor=c;ctx.fillStyle='#090b10';ctx.fillRect(-s*.55,-s*.05,s*.18,s*.55);ctx.fillRect(s*.37,-s*.05,s*.18,s*.55);ctx.fillStyle=c;ctx.beginPath();ctx.moveTo(-s*.42,s*.32);ctx.lineTo(-s*.28,-s*.22);ctx.lineTo(0,-s*.42);ctx.lineTo(s*.28,-s*.22);ctx.lineTo(s*.42,s*.32);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#101724';ctx.fillRect(-s*.18,-s*.2,s*.36,s*.35);ctx.fillStyle='#fff';ctx.fillRect(-s*.06,-s*.06,s*.12,s*.12);ctx.restore()}
function drawParticles(w,h){const motion=player.speed/210;ctx.strokeStyle='#dbe9ff44';ctx.lineWidth=1;for(let i=0;i<28;i++){const seed=(i*83+Math.floor(performance.now()*.04*motion))%997,x=(seed*17)%w,y=h*.35+(seed*11)%(h*.65);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(x-w/2)*.018*motion,y+10+30*motion);ctx.stroke()}}
function loop(now){const dt=Math.min(.035,(now-last)/1000);last=now;update(dt,now);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
